version: '3'
services:
  jarvis-bot:
    build: .
    restart: unless-stopped
    # Вот этот блок передаст переменные из Portainer внутрь контейнера
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PHONE_IP=${PHONE_IP}
