version: '3.8'
services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      # Адрес теперь указывает на контейнер llama_cpp_server
      - LLM_URL=http://llama_cpp_server:8080/v1/chat/completions
    volumes:
      - bot_memory:/app/data
    networks:
      - ai_network

volumes:
  bot_memory:

networks:
  ai_network:
    external: true
